/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Business.Hospital.Model.HospitalDirectory;
import Bussiness.Admin.Admin;
import Bussiness.EmergencyResponseTeam.Ersteam;
import Bussiness.Government.governor;
import Bussiness.SearchandResue.Searchandresqueteam;
import Bussiness.SearchandResue.Searchreq;
import Fundraisingteam.Fundigteam;
import Team.Allteam;
import Model.Diastermangdirectory;
import Model.Directoryinti;
import Model.Test;
import Person.Personcitizen;
import Person.Personteam;
import UI.Admin.Manggebyadmin;
import UI.Fundraising.Fundraisinghome;
import UI.Person.Personhome;
import UI.Reliefteam.NormalrequestUI;
import UITest.Createdisaster;
import UIers.Ershome;
import UIgovernmnet.Governmentperson;
import UIlogistics.LgoisticsHome;
import UserInterface.LoginPageJPanel;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.awt.Image; // For Image class
import java.awt.Graphics; // For Graphics class
import java.awt.BorderLayout; // For BorderLayout class
import javax.swing.ImageIcon; // For ImageIcon class

/**
 *
 * @author devmi
 */
public class NewJFrame extends javax.swing.JFrame {

    Directoryinti Person;
        Directoryinti Persont;

   Directoryinti ers;
    Directoryinti gov;
    Directoryinti logteam;
     Directoryinti diaster;
         Directoryinti logrep;
         Directoryinti  ersreporters;
         Directoryinti request;
         Directoryinti  volun;
         Directoryinti req;
         Directoryinti searchandrescue;
         Directoryinti   test;
         Directoryinti ad;
         Directoryinti fundigteam;
         Directoryinti srq;
          HospitalDirectory hd;
    
         
    /**
     * Creates new form NewJFrame
     * @param Person
     */
    public NewJFrame() {
        initComponents();
                this.hd = new HospitalDirectory();

       srq = new Directoryinti();
    
       Person = new Directoryinti();
       ers = new Directoryinti();
       gov = new Directoryinti();
       logteam = new Directoryinti();
       diaster =   new Directoryinti();     
       Persont = new Directoryinti();   
       logrep = new Directoryinti();
       ersreporters = new Directoryinti();
       request = new Directoryinti();
       volun = new Directoryinti();
       req = new Directoryinti();
       searchandrescue = new Directoryinti();
       fundigteam = new Directoryinti();
       test = new Directoryinti();
       ad = new Directoryinti();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtpassword = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        userProcessContainer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("User Name:");

        jLabel3.setText("Password: ");

        btnLogin.setBackground(new java.awt.Color(0, 204, 204));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        jButton1.setText("Hospital Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setText("Logout");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Analytics");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(78, 78, 78)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(480, 480, 480)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(jPanel1);

        userProcessContainer.setBackground(new java.awt.Color(255, 255, 255));
        userProcessContainer.setLayout(new java.awt.CardLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Response Large.jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");
        userProcessContainer.add(jLabel1, "card2");

        jSplitPane1.setRightComponent(userProcessContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 764, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
     String id = txtid.getText();
String p_password = txtpassword.getText();

boolean accessGranted = false;

// Check for 'Personteam' users
for (Personteam p : Persont.getPersont()) {
    if (p.getId().equals(id) && p.getPassword().equals(p_password)) {
        accessGranted = true;
        if (p.getTeam().equals("Ersteam")) {
            JOptionPane.showMessageDialog(this, "Access Granted");
            Ershome panel = new Ershome(userProcessContainer, diaster, id, Persont, ersreporters);
            navigateToPanel(panel, "Ershome");
        } else if (p.getTeam().equals("Logs")) {
            JOptionPane.showMessageDialog(this, "Access Granted");
            LgoisticsHome panel = new LgoisticsHome(userProcessContainer, diaster, id, Persont, ersreporters,logrep);
            navigateToPanel(panel, "LgoisticsHome");
        }
         else if (p.getTeam().equals("Logistics")) {
            JOptionPane.showMessageDialog(this, "Access Granted");
            LgoisticsHome panel = new LgoisticsHome(userProcessContainer, diaster, id, Persont, ersreporters,logrep);
            navigateToPanel(panel, "LgoisticsHome");
        }
        break;
    }
}

if (!accessGranted) {
    for (governor g : gov.getGov()) {
        if (id.equals(String.valueOf(g.getLoginId())) && p_password.equals(g.getPassword())) {
            JOptionPane.showMessageDialog(this, "Access Granted");
            Governmentperson panel = new Governmentperson(userProcessContainer, diaster, id, gov, logrep, volun, request);
            navigateToPanel(panel, "Governmentperson");
            accessGranted = true;
            break;
        }
    }
    for(Fundigteam f:fundigteam.getFundigteam())
    {
        if(f.getTeamname().equals(id) && p_password.equals(f.getPassword()))
        {
            JOptionPane.showMessageDialog(this, "Access Granted");
            Fundraisinghome panel = new Fundraisinghome(userProcessContainer, request, Persont, id);
            navigateToPanel(panel, "Fundraisinghome");
            accessGranted = true;
            break;
        }
    }
    for(Admin f:ad.getAd())
    {
        if(f.getId().equals(id) && p_password.equals(f.getPassword()))
        {
            JOptionPane.showMessageDialog(this, "Access Granted");
            Manggebyadmin panel = new Manggebyadmin(logteam,Persont,userProcessContainer, ers,diaster, id, gov, logrep, volun,request);
            navigateToPanel(panel, "Manggebyadmin");
            accessGranted = true;
            break;
        }
    } 
    for(Test f:test.getTest())
    {
        if(f.getId().equals(id) && p_password.equals(f.getPassword()))
        {
            JOptionPane.showMessageDialog(this, "Access Granted");
            Createdisaster panel = new Createdisaster(userProcessContainer,diaster);
            navigateToPanel(panel, "Createdisaster");
            accessGranted = true;
            break;
            
            
        }
    }
     for(Personcitizen f:Person.getPerson())
    {
        if(f.getId().equals(id) && p_password.equals(f.getPassword()))
        {
            JOptionPane.showMessageDialog(this, "Access Granted");
            String name= f.getName();
            Personhome panel = new Personhome( userProcessContainer,  id,  Person,  volun,    searchandrescue, request, name);
            navigateToPanel(panel, "Personhome1");
            accessGranted = true;
            break;
        }
    }
     
     for(Searchandresqueteam f:srq.getSrq())
    {
        if(f.getTeamname().equals(id) && p_password.equals(f.getTotalsize()))
        {
            JOptionPane.showMessageDialog(this, "Access Granted");
            NormalrequestUI panel = new NormalrequestUI( searchandrescue, id, userProcessContainer, Persont );
            navigateToPanel(panel, "NormalrequestUI");
            accessGranted = true;
            break;
        }
}
}
// Access Denied
if (!accessGranted) {
    JOptionPane.showMessageDialog(this, "Access Denied");
}

// Reset fields
txtid.setText("");
txtpassword.setText("");
    }

// Method to navigate to a new panel
private void navigateToPanel(JPanel panel, String name) {
    userProcessContainer.add(name, panel);
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.next(userProcessContainer);


    }//GEN-LAST:event_btnLoginActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JPanel loginPage = new LoginPageJPanel(userProcessContainer,hd);
        userProcessContainer.add("LoginPageJPanel", loginPage);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         JPanel logout = new logout(userProcessContainer);
        userProcessContainer.add("LoginPageJPanel", logout);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        NewJPanel panel = new NewJPanel( diaster,Persont, ersreporters,  hd);
        userProcessContainer.add("NewJPanel", panel);
        CardLayout layout =(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    
    class BackgroundPanel extends JPanel {
    private Image backgroundImage;

    public BackgroundPanel(String imagePath) {
        backgroundImage = new ImageIcon(imagePath).getImage();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        g.drawImage(backgroundImage, 0, 0, this.getWidth(), this.getHeight(), this);
    }
}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables
}
