/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UIers;

import Model.Diastermangdirectory;
import Model.Directoryinti;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.ImageIcon;
import java.awt.Image;
/**
 *
 * @author devmi
 */
public class Ershome extends javax.swing.JPanel {

        JPanel userProcessContainer;
Directoryinti diaster;
Directoryinti Persont;
String id;
Directoryinti ersreporters;
    /**
     * Creates new form Ershome
     */
    public Ershome(JPanel userProcessContainer, Directoryinti diaster,String id,Directoryinti Persont,Directoryinti ersreporters) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.diaster = diaster;
        this.id = id;
        this.Persont = Persont;
        this.ersreporters = ersreporters;
        popolaeearth();

    }
    
    public void popolaeearth()
    {
        
    int n =0;
        for (Diastermangdirectory diaster : diaster.getDiaster()) 
{
        if (diaster.getDisname().equals("Earthquake") && diaster.getStatus().equals("INPROGRESS"))
        {
            n++;
        }
}
        
       int n1 =0;
        for (Diastermangdirectory diaster : diaster.getDiaster() ) 
{
        if (diaster.getDisname().equals("Floods") && diaster.getStatus().equals("INPROGRESS"))
        {
            n1++;
        }
}
        
       int n2 =0;
        for (Diastermangdirectory diaster : diaster.getDiaster()) 
{
        if (diaster.getDisname().equals("Cyclone")&& diaster.getStatus().equals("INPROGRESS"))
        {
            n2++;
        }
}
        
      int  n3 =0;
        for (Diastermangdirectory diaster : diaster.getDiaster()) 
{
        if (diaster.getDisname().equals("Tsunami")&& diaster.getStatus().equals("INPROGRESS"))
        {
            n3++;
        }
}
        
      int  n4 =0;
        for (Diastermangdirectory diaster : diaster.getDiaster()) 
{
        if (diaster.getDisname().equals("Forest-Fire")&& diaster.getStatus().equals("INPROGRESS"))
        {
            n4++;
        }
}
        
      int  n5 =0;
        for (Diastermangdirectory diaster : diaster.getDiaster()) 
{
        if (diaster.getDisname().equals("Others")&& diaster.getStatus().equals("INPROGRESS"))
        {
            n5++;
        }
}
        txtcyclone.setText(String.valueOf(n2));
        
  
        
    txtofearthqcnt.setText(String.valueOf(n));
        
        txttsunmaicnt.setText(String.valueOf(n3));
        
    
        
    txtforstfiers.setText(String.valueOf(n4));

}
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtofearthqcnt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txttsunmaicnt = new javax.swing.JTextField();
        txtforstfiers = new javax.swing.JTextField();
        txtcyclone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnearthquake = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Tsunami");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 108, 32));

        txtofearthqcnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtofearthqcntActionPerformed(evt);
            }
        });
        jPanel2.add(txtofearthqcnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 70, 60));

        jLabel2.setText("Cyclone");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 108, 32));

        jLabel3.setText("EarthQuake");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 108, 32));

        txttsunmaicnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttsunmaicntActionPerformed(evt);
            }
        });
        jPanel2.add(txttsunmaicnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 70, 60));
        jPanel2.add(txtforstfiers, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 369, 57, 62));
        jPanel2.add(txtcyclone, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 70, 60));

        jLabel6.setText("Forest fire");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 306, 108, 32));

        btnearthquake.setText("View");
        btnearthquake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnearthquakeActionPerformed(evt);
            }
        });
        jPanel2.add(btnearthquake, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        jButton9.setText("View");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, -1, -1));

        jButton10.setText("View");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, -1, -1));

        jButton11.setText("View");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 476, -1, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 1570, 810));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel7.setBackground(new java.awt.Color(153, 153, 255));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Home Page");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 1170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(338, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1710, -1));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        jButton5.setText("Settings");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton7.setText("Home");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton2.setText("Work Area");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 23, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(613, Short.MAX_VALUE))
        );

        add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 140, 800));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

         Settingers panel = new Settingers(userProcessContainer, diaster,id,Persont);
        userProcessContainer.add("Settingers", panel);
        CardLayout layout =(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
       
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:

        Ershome panel = new Ershome(userProcessContainer, diaster,id,Persont, ersreporters);
        userProcessContainer.add("Ershome", panel);
        CardLayout layout =(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnearthquakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnearthquakeActionPerformed
        DisaterView panel = new DisaterView(userProcessContainer, diaster,id,Persont,"Earthquake",ersreporters);
        userProcessContainer.add("DisaterView", panel);
        CardLayout layout =(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnearthquakeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        PersonERs panel;
            panel = new PersonERs(userProcessContainer, diaster,id,Persont, ersreporters);
        userProcessContainer.add("Ersperson", panel);
        CardLayout layout =(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        DisaterView panel = new DisaterView(userProcessContainer, diaster,id,Persont,"Tsunami",ersreporters);
        userProcessContainer.add("DisaterView", panel);
        CardLayout layout =(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        DisaterView panel = new DisaterView(userProcessContainer, diaster,id,Persont,"Cyclone",ersreporters);
        userProcessContainer.add("DisaterView", panel);
        CardLayout layout =(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        DisaterView panel = new DisaterView(userProcessContainer, diaster,id,Persont,"Forest-Fire",ersreporters);
        userProcessContainer.add("DisaterView", panel);
        CardLayout layout =(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void txtofearthqcntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtofearthqcntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtofearthqcntActionPerformed

    private void txttsunmaicntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttsunmaicntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttsunmaicntActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnearthquake;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField txtcyclone;
    private javax.swing.JTextField txtforstfiers;
    private javax.swing.JTextField txtofearthqcnt;
    private javax.swing.JTextField txttsunmaicnt;
    // End of variables declaration//GEN-END:variables
}
