/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UIlogistics;

import Bussiness.EmergencyResponseTeam.Ersreport;
import Model.Directoryinti;
import Model.Reportforlogistics;
import UIers.Settingers;
import java.awt.CardLayout;
import javax.swing.JPanel;
 import javax.swing.JOptionPane;

/**
 *
 * @author devmi
 */
public class Report extends javax.swing.JPanel {
 JPanel userProcessContainer;
 Directoryinti ersreporters;
Directoryinti Persont;
Directoryinti logrep;
Directoryinti diaster;
String idd;
String id;
String tt;

    /**
     * Creates new form Report
     */
    public Report(Directoryinti logrep,JPanel userProcessContainer, Directoryinti diaster,String id,Directoryinti Persont,Directoryinti ersreporters,String idd,String tt) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
        this.diaster = diaster;
        this.id = id;
        this.Persont = Persont;
        this.idd=idd;
        this.tt= tt;
        this.ersreporters = ersreporters;
         this.logrep = logrep;
        populatefirlds();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        txtvolreq = new javax.swing.JTextField();
        txtvehiclerq = new javax.swing.JTextField();
        txtshel = new javax.swing.JTextField();
        txtfundreq = new javax.swing.JTextField();
        txtfoodpackreq = new javax.swing.JTextField();
        txtmedicalsuppreq = new javax.swing.JTextField();
        txtbalnkreq = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Save = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 460, 160));

        txtvolreq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvolreqActionPerformed(evt);
            }
        });
        jPanel3.add(txtvolreq, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 162, -1));

        txtvehiclerq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvehiclerqActionPerformed(evt);
            }
        });
        jPanel3.add(txtvehiclerq, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 162, -1));
        jPanel3.add(txtshel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 162, -1));
        jPanel3.add(txtfundreq, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 180, 121, -1));
        jPanel3.add(txtfoodpackreq, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 250, 121, -1));

        txtmedicalsuppreq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmedicalsuppreqActionPerformed(evt);
            }
        });
        jPanel3.add(txtmedicalsuppreq, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 310, 121, -1));
        jPanel3.add(txtbalnkreq, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 370, 121, -1));

        jLabel4.setText("Number of Volunters Required");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 180, -1));

        jLabel5.setText("Number of Vehicles Required");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 200, -1));

        jLabel6.setText("Total fund for recovery");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 160, -1));

        jLabel7.setText("Number of Medical Supplies");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, -1, -1));

        jLabel9.setText("Number of shelters to be built");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 230, -1));

        jLabel11.setText("Number of food packets");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 160, -1));

        jLabel12.setText("Description");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 85, -1));

        jLabel13.setText("Number of blankets");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 130, -1));

        Save.setText("Submit");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        jPanel3.add(Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 430, 110, 40));

        jButton2.setText("Save Changes");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 500, 120, 40));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOGISTICS TEAM REPORT");

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addComponent(jButton1))
                .addGap(23, 23, 23))
        );

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 850, -1));

        jScrollPane2.setViewportView(jPanel3);

        jScrollPane3.setViewportView(jScrollPane2);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 880, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 915, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtvolreqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvolreqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvolreqActionPerformed

    private void txtvehiclerqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvehiclerqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvehiclerqActionPerformed

    private void txtmedicalsuppreqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmedicalsuppreqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmedicalsuppreqActionPerformed

    public void populatefirlds(){
        
     for(Reportforlogistics e: logrep.getLogrep()){
        if(e.getDiaster_id().equals(idd)){
            txtbalnkreq.setText(String.valueOf(e.getBlankets()));
            txtfundreq.setText(String.valueOf(e.getCompensatation()));
            txtmedicalsuppreq.setText(e.getMedicalsupplies());
            txtshel.setText(String.valueOf(e.getPropertiy_sheltertobuils()));
            txtvehiclerq.setText(String.valueOf(e.getNumber_ofvehicles()));
            txtvolreq.setText(String.valueOf(e.getNumber_ofvolunteers()));
            jTextArea1.setText(e.getDescri());
            txtfoodpackreq.setText(String.valueOf(e.getFoodpackets()));
        }
    
        
    }
    }
    
    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed

boolean dataSaved = false;

for(Reportforlogistics usc: logrep.getLogrep()){
    if(usc.getDiaster_id().equals(idd)){

        try {
            double numberOfVolunteers = Double.parseDouble(txtvolreq.getText());
            double numberOfVehicles = Double.parseDouble(txtvehiclerq.getText());
            double propertyShelterToBuild = Double.parseDouble(txtshel.getText());
            double compensation = Double.parseDouble(txtfundreq.getText());
            double foodPackets = Double.parseDouble(txtfoodpackreq.getText());
            double blankets = Double.parseDouble(txtbalnkreq.getText());

            usc.setNumber_ofvolunteers(numberOfVolunteers);
            usc.setNumber_ofvehicles(numberOfVehicles);
            usc.setPropertiy_sheltertobuils(propertyShelterToBuild);
            usc.setCompensatation(compensation);
            usc.setFoodpackets(foodPackets);
            usc.setBlankets(blankets);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid numerical input", "Warning", JOptionPane.WARNING_MESSAGE);
            continue; 
        }

        String medicalSupplies = txtmedicalsuppreq.getText();
        if(medicalSupplies.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Medical supplies field cannot be empty", "Warning", JOptionPane.WARNING_MESSAGE);
            continue; 
        }

        usc.setMedicalsupplies(medicalSupplies);
        usc.setDescri(jTextArea1.getText());
        usc.setStatus("COMPLETE");
        dataSaved = true; 
    }
}

if(dataSaved) {
    JOptionPane.showMessageDialog(null, "Report Submitted successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
}

       
                // TODO add your handling code here:
    }//GEN-LAST:event_SaveActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
  

boolean dataUpdated = false;

for(Reportforlogistics usc: logrep.getLogrep()){
    if(usc.getDiaster_id().equals(idd)){

        try {
            double numberOfVolunteers = Double.parseDouble(txtvolreq.getText());
            double numberOfVehicles = Double.parseDouble(txtvehiclerq.getText());
            double propertyShelterToBuild = Double.parseDouble(txtshel.getText());
            double compensation = Double.parseDouble(txtfundreq.getText());
            double foodPackets = Double.parseDouble(txtfoodpackreq.getText());
            double blankets = Double.parseDouble(txtbalnkreq.getText());
            String medicalSupplies = txtmedicalsuppreq.getText();

            if(medicalSupplies.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Medical supplies field cannot be empty", "Warning", JOptionPane.WARNING_MESSAGE);
                continue; 
            }

            // Setting the values
            usc.setNumber_ofvolunteers(numberOfVolunteers);
            usc.setNumber_ofvehicles(numberOfVehicles);
            usc.setPropertiy_sheltertobuils(propertyShelterToBuild);
            usc.setCompensatation(compensation);
            usc.setFoodpackets(foodPackets);
            usc.setMedicalsupplies(medicalSupplies);
            usc.setBlankets(blankets);
            usc.setDescri(jTextArea1.getText());
            usc.setStatus("INPROGRESS");

            dataUpdated = true; // Mark that data has been successfully updated

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid numerical input", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }
}

if(dataUpdated) {
    JOptionPane.showMessageDialog(null, "Reort Stored Successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
}

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Save;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtbalnkreq;
    private javax.swing.JTextField txtfoodpackreq;
    private javax.swing.JTextField txtfundreq;
    private javax.swing.JTextField txtmedicalsuppreq;
    private javax.swing.JTextField txtshel;
    private javax.swing.JTextField txtvehiclerq;
    private javax.swing.JTextField txtvolreq;
    // End of variables declaration//GEN-END:variables
}
