/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UIlogistics;

import Bussiness.EmergencyResponseTeam.Ersreport;
import Model.Directoryinti;
import Model.Reportforlogistics;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author devmi
 */
public class ReportView extends javax.swing.JPanel {

   JPanel userProcessContainer;
 Directoryinti ersreporters;
Directoryinti Persont;
Directoryinti logrep;
Directoryinti diaster;
String idd;
String id;
String tt;

    /**
     * Creates new form Report
     */
    public ReportView(Directoryinti logrep,JPanel userProcessContainer, Directoryinti diaster,String id,Directoryinti Persont,Directoryinti ersreporters,String idd,String tt) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
        this.diaster = diaster;
        this.id = id;
        this.Persont = Persont;
        this.idd=idd;
        this.tt= tt;
        this.ersreporters = ersreporters;
        this.logrep = logrep;
    populatefirlds();}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        txtdisid = new javax.swing.JTextField();
        txtvolreq = new javax.swing.JTextField();
        txtvehiclerq = new javax.swing.JTextField();
        txtshel = new javax.swing.JTextField();
        txtfundreq = new javax.swing.JTextField();
        txtfoodpackreq = new javax.swing.JTextField();
        txtmedicalsuppreq = new javax.swing.JTextField();
        txtbalnkreq = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 510, 460, 160));
        jPanel3.add(txtdisid, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 162, -1));

        txtvolreq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvolreqActionPerformed(evt);
            }
        });
        jPanel3.add(txtvolreq, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 162, -1));

        txtvehiclerq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvehiclerqActionPerformed(evt);
            }
        });
        jPanel3.add(txtvehiclerq, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 162, -1));
        jPanel3.add(txtshel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 162, -1));
        jPanel3.add(txtfundreq, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, 121, -1));
        jPanel3.add(txtfoodpackreq, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 240, 121, -1));

        txtmedicalsuppreq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmedicalsuppreqActionPerformed(evt);
            }
        });
        jPanel3.add(txtmedicalsuppreq, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 300, 121, -1));
        jPanel3.add(txtbalnkreq, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 370, 121, -1));

        jLabel3.setText("Disaster id");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 76, -1));

        jLabel4.setText("Number of Volunters Required");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 180, -1));

        jLabel5.setText("Number of Vehicles Required");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 170, -1));

        jLabel6.setText("Total fund for recovery");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 130, -1));

        jLabel7.setText("Number of Medical Supplies");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, -1, -1));

        jLabel9.setText("Number of shelters to be built");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 180, 20));

        jLabel11.setText("Number of food packets");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 150, -1));

        jLabel12.setText("Description");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, 85, -1));

        jLabel13.setText("Number of blankets");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 140, -1));

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 430, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOGISTICS TEAM REPORT");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 734, 180));

        jScrollPane2.setViewportView(jPanel3);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2, 1030, 830));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1039, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtmedicalsuppreqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmedicalsuppreqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmedicalsuppreqActionPerformed

    private void txtvehiclerqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvehiclerqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvehiclerqActionPerformed

    private void txtvolreqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvolreqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvolreqActionPerformed

public void populatefirlds(){
    

    for(Reportforlogistics e: logrep.getLogrep()){
        if(e.getDiaster_id().equals(idd)){
            txtdisid.setText(idd);
            txtbalnkreq.setText(String.valueOf(e.getBlankets()));
            txtfundreq.setText(String.valueOf(e.getCompensatation()));
            txtmedicalsuppreq.setText(e.getMedicalsupplies());
            txtshel.setText(String.valueOf(e.getPropertiy_sheltertobuils()));
            txtvehiclerq.setText(String.valueOf(e.getNumber_ofvehicles()));
            txtvolreq.setText(String.valueOf(e.getNumber_ofvolunteers()));
            jTextArea1.setText(e.getDescri());
        }
    }
        }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtbalnkreq;
    private javax.swing.JTextField txtdisid;
    private javax.swing.JTextField txtfoodpackreq;
    private javax.swing.JTextField txtfundreq;
    private javax.swing.JTextField txtmedicalsuppreq;
    private javax.swing.JTextField txtshel;
    private javax.swing.JTextField txtvehiclerq;
    private javax.swing.JTextField txtvolreq;
    // End of variables declaration//GEN-END:variables
}
