/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Managepeopleandteams;

import Bussiness.EmergencyResponseTeam.Ersreport;
import Bussiness.EmergencyResponseTeam.Ersteam;
import Model.Directoryinti;
import Model.Reportforlogistics;
import Person.Personteam;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
  import javax.swing.JOptionPane;

/**
 *
 * @author devmi
 */
public class Viewpplinteams extends javax.swing.JPanel {
JPanel userProcessContainer;
Directoryinti Persont;

    /**
     * Creates new form ManagepplUI
     */
    public Viewpplinteams(JPanel userProcessContainer,Directoryinti Persont) {
        initComponents();
                this.Persont = Persont;
        this.userProcessContainer = userProcessContainer;
        populatetab();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        employeeTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        nameTxtField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        txtpassword = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        txtaddress = new javax.swing.JTextField();
        txtdob = new javax.swing.JTextField();
        txtcity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtphn = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        selectOrganizationJComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addBtn.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Managepeopleandteams/add.png"))); // NOI18N
        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        jPanel1.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 120, -1));

        employeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Team Name", "Name"
            }
        ));
        jScrollPane1.setViewportView(employeeTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 460, 460));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica", 1, 24)); // NOI18N
        jLabel1.setText("Manage Organization Employee");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 46, -1, 40));

        backBtn.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Managepeopleandteams/Back.png"))); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel2.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 46, -1, 29));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1168, 112));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jLabel4.setText("Name       ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 197, 70, -1));
        jPanel1.add(nameTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 195, 240, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jLabel7.setText("Sex          ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 80, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 246, 240, 30));
        jPanel1.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 240, -1));
        jPanel1.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 240, -1));
        jPanel1.add(txtaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 240, -1));
        jPanel1.add(txtdob, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 240, -1));
        jPanel1.add(txtcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, 240, -1));

        jLabel5.setText("Password");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        jLabel6.setText("Id");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 20, -1));

        jLabel8.setText("Address");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, -1, -1));

        jLabel9.setText("Date of Birth");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, -1, -1));

        jLabel11.setText("City");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 40, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Managepeopleandteams/trash.png"))); // NOI18N
        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 130, -1, -1));
        jPanel1.add(txtphn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 550, 240, -1));

        jLabel14.setText("Phone number");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 550, -1, -1));

        selectOrganizationJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ersteam", "Logistics" }));
        jPanel1.add(selectOrganizationJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 600, 240, -1));

        jLabel3.setText("Function");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 600, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 767));

        jLabel10.setText("State");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 773, -1, -1));

        jLabel13.setText("Password");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 885, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
public void populatetab(){

     DefaultTableModel dtm = (DefaultTableModel) employeeTable.getModel();
                dtm.setRowCount(0);        
for (Personteam dis : Persont.getPersont()) 
{
           Object[] row = new Object[3];
            row[0] = dis;
            row[1] = dis.getTeam();
            row[2] = dis.getName();
                    dtm.addRow(row);
}         
}
    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed


try {
    String address = txtaddress.getText();
    String password = txtpassword.getText();
    String city = txtcity.getText();
    String dob = txtdob.getText(); // Date of Birth
    String id = txtid.getText();
    String name = nameTxtField.getText();
    String phoneText = txtphn.getText();
    String department = (String) selectOrganizationJComboBox.getSelectedItem();

    // Validation for empty fields
    if(address.isEmpty() || password.isEmpty() || city.isEmpty() || dob.isEmpty() ||
       id.isEmpty() || name.isEmpty() || phoneText.isEmpty() || department.isEmpty()) {
        JOptionPane.showMessageDialog(null, "All fields must be filled", "Warning", JOptionPane.WARNING_MESSAGE);
        return; // Stop further execution
    }

   
    int phoneNo = Integer.parseInt(phoneText);

    // If all validations pass, set the values
    Personteam usc = Persont.addNewPersont();
    usc.setAddress(address);
    usc.setPassword(password);
    usc.setCity(city);
    usc.setDob(dob);
    usc.setId(id);
    usc.setName(name);
    usc.setPhoneno(String.valueOf(phoneNo));
    usc.setTeam(department);

} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(null, "Invalid phone number format", "Warning", JOptionPane.WARNING_MESSAGE);
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "An error occurred: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}


              
    }//GEN-LAST:event_addBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JTable employeeTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameTxtField;
    private javax.swing.JComboBox selectOrganizationJComboBox;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtcity;
    private javax.swing.JTextField txtdob;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JTextField txtphn;
    // End of variables declaration//GEN-END:variables
}
