/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Fundraising;

import Bussiness.EmergencyResponseTeam.Ersreport;
import Fundraisingteam.Requestin;
import Model.Diastermangdirectory;
import Model.Directoryinti;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author devmi
 */
public class Fundraisinghome extends javax.swing.JPanel {

    Directoryinti request;
    Directoryinti Persont;
    JPanel userProcessContainer;
    String id;
    /**
     * Creates new form NewJPanel
     */
    public Fundraisinghome(JPanel userProcessContainer, Directoryinti request,Directoryinti Persont,String id) {
        initComponents();
        this.request = request;
        this.userProcessContainer = userProcessContainer;
        this.Persont = Persont;
        this.id = id;
        populatetab1(); 
        populatetab2(); 
    }
    
    public void  populatetab1(){
         DefaultTableModel dtm = (DefaultTableModel) requestJTable2.getModel();
                dtm.setRowCount(0);        
for (Requestin dis : request.getRequest()) 
{
        if (dis.getStatus().equals("COMPLETE"))
        {
            Object[] row = new Object[4];
            row[0] = dis;
            row[1] = dis.getReason();
            row[2] = dis.getRequestedby();
            row[3] = dis.getDescription();
     
           

            
            dtm.addRow(row);
        }
        }
   }
        
    
        
           public void  populatetab2(){
         DefaultTableModel dtm = (DefaultTableModel) tbl2.getModel();
                dtm.setRowCount(0);        
for (Requestin dis : request.getRequest()) 
{
        if (dis.getStatus().equals("ONGOING"))
        {
            Object[] row = new Object[4];
            row[0] = dis;
            row[1] = dis.getReason();
            row[2] = dis.getRequestedby();
            row[3] = dis.getDescription();
     
           

            
            dtm.addRow(row);
        }
        }
   }
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl2 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtcustomerid1 = new javax.swing.JTextField();
        txtamountraised1 = new javax.swing.JTextField();
        txtstate1 = new javax.swing.JTextField();
        txtamtreq1 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtarearrr = new javax.swing.JTextArea();
        Status = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnnn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        requestJTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 0));
        jPanel2.setToolTipText("");
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 240, 240));
        jLabel1.setFont(new java.awt.Font("Helvetica", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Fundraising/Back.png"))); // NOI18N
        jLabel1.setText("                                                                                       Fund Raiser Work Area");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-180, 0, 1480, 70));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Fundraising/Back.png"))); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 90, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel3.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        jLabel3.setText("COMPLETED REQUEST HISTORY ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, -1));

        tbl2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Subject", "Name of User", "Description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbl2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 150, 490, 153));

        jLabel4.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        jLabel4.setText("ONGOING REQUEST HISTORY ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 100, -1, -1));

        txtcustomerid1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcustomerid1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtcustomerid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, 180, -1));
        jPanel1.add(txtamountraised1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 490, 180, -1));
        jPanel1.add(txtstate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 550, 190, -1));
        jPanel1.add(txtamtreq1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 600, 180, -1));

        txtarearrr.setColumns(20);
        txtarearrr.setRows(5);
        jScrollPane3.setViewportView(txtarearrr);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 420, 480, 130));

        Status.setText("Status");
        jPanel1.add(Status, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 550, 50, 20));

        jLabel6.setText("Amount Required");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 600, -1, -1));

        jLabel7.setText("Customer Id");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, -1, 20));

        jLabel8.setText("Amount Raised");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, -1, 20));

        btnnn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Fundraising/View.png"))); // NOI18N
        btnnn.setText("View");
        btnnn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnnActionPerformed(evt);
            }
        });
        jPanel1.add(btnnn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, -1, -1));

        jLabel9.setText("Description");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 430, -1, -1));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Fundraising/Home.png"))); // NOI18N
        jButton8.setText("Home");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Fundraising/Make A Requestr.png"))); // NOI18N
        jButton9.setText("Make a Request");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(273, Short.MAX_VALUE)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(315, 315, 315))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 150, 730));

        requestJTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Subject", "Name of User", "Description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(requestJTable2);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 480, 153));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Fundraising/View.png"))); // NOI18N
        jButton1.setText("View");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 350, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:

        Fundraisinghome panel = new Fundraisinghome(userProcessContainer,Persont, request,id);
        userProcessContainer.add("Fundraisinghome", panel);
        CardLayout layout =(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        Donationreq panel = new Donationreq(userProcessContainer,  Persont,request,id);
        userProcessContainer.add("Donationreq", panel);
        CardLayout layout =(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void txtcustomerid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcustomerid1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcustomerid1ActionPerformed

    private void btnnnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnnActionPerformed
        // TODO add your handling code here:
         
        int selectedRow = requestJTable2.getSelectedRow();
        if(selectedRow < 0){
              JOptionPane.showMessageDialog(null, "Please select a row from table to view details", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else{
            DefaultTableModel model = (DefaultTableModel) requestJTable2.getModel();
            Requestin disaster = (Requestin) model.getValueAt(selectedRow, 0);
             txtamountraised1.setText(String.valueOf(disaster.getAmountraised()));
             txtamtreq1.setText(String.valueOf(disaster.getAmount()));
             txtstate1.setText(disaster.getStatus());
             txtcustomerid1.setText(disaster.getId());
             txtarearrr.setText(disaster.getDescription());
        }
    
    }//GEN-LAST:event_btnnnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = tbl2.getSelectedRow();
        if(selectedRow < 0){
              JOptionPane.showMessageDialog(null, "Please select a row from table to view details", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else{
            DefaultTableModel model = (DefaultTableModel) tbl2.getModel();
            Requestin disaster = (Requestin) model.getValueAt(selectedRow, 0);
             txtamountraised1.setText(String.valueOf(disaster.getAmountraised()));
             txtamtreq1.setText(String.valueOf(disaster.getAmount()));
             txtstate1.setText(disaster.getStatus());
             txtcustomerid1.setText(disaster.getId());
                          txtarearrr.setText(disaster.getDescription());

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Status;
    private javax.swing.JButton btnnn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable requestJTable2;
    private javax.swing.JTable tbl2;
    private javax.swing.JTextField txtamountraised1;
    private javax.swing.JTextField txtamtreq1;
    private javax.swing.JTextArea txtarearrr;
    private javax.swing.JTextField txtcustomerid1;
    private javax.swing.JTextField txtstate1;
    // End of variables declaration//GEN-END:variables
}
